CREATE TABLE Hall (
Id INT PRIMARY KEY,
Name VARCHAR(255),
);
CREATE TABLE Row (
Id INT PRIMARY KEY,
Number INT NOT NULL,
);
CREATE TABLE Place (
Id INT PRIMARY KEY,
Capacity INT NOT NULL,
RowId INT NOT NULL,
FOREIGN KEY (RowId) REFERENCES Row(Id),
);
CREATE TABLE Ticket (
Id INT PRIMARY KEY,
IsSold BIT NOT NULL,
PlaceId INT NOT NULL,
FOREIGN KEY (PlaceId) REFERENCES Place(Id),
);
CREATE TABLE Movie (
Id INT PRIMARY KEY,
Name VARCHAR(255),
Description VARCHAR(255),
Duration INT NOT NULL,
);
CREATE TABLE Session (
Id INT PRIMARY KEY,
Start DATETIME NOT NULL,
MovieId INT NOT NULL,
HallId INT NOT NULL,
DateOfSale DATETIME NOT NULL,
FOREIGN KEY (MovieId) REFERENCES Movie(Id),
FOREIGN KEY (HallId) REFERENCES Hall(Id),
);
CREATE TABLE Genre (
Id INT PRIMARY KEY,
Name VARCHAR(255),
Description VARCHAR(255),
);
CREATE TABLE MovieGenre (
MovieId INT NOT NULL,
GenreId INT NOT NULL,
FOREIGN KEY (MovieId) REFERENCES Movie(Id),
FOREIGN KEY (GenreId) REFERENCES Genre(Id),
PRIMARY KEY (MovieId, GenreId)
);
