CREATE TABLE Position (
Id INT PRIMARY KEY,
Name VARCHAR(255),
);
CREATE TABLE Department (
Id INT PRIMARY KEY,
Name VARCHAR(255),
);
CREATE TABLE Employee (
Id INT PRIMARY KEY,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255),
PositionId INT NOT NULL,
DepartmentId INT NOT NULL,
FOREIGN KEY (PositionId) REFERENCES Position(Id),
FOREIGN KEY (DepartmentId) REFERENCES Department(Id),
);
CREATE TABLE PartOfTimeSheet (
Id INT PRIMARY KEY,
DayOfDate DATE,
Hours INT NOT NULL,
EmployeedId INT NOT NULL,
FOREIGN KEY (EmployeedId) REFERENCES Employee(Id),
);