CREATE TABLE SomeGroup (
Id INT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
NumberOfStudents INT NOT NULL,
);
CREATE TABLE Student (
Id INT PRIMARY KEY,
FullName VARCHAR(255) NOT NULL,
GroupId INT NOT NULL,
FOREIGN KEY (GroupId) REFERENCES SomeGroup(Id),
);
CREATE TABLE Teacher (
Id INT PRIMARY KEY,
FullName VARCHAR(255) NOT NULL,
);
CREATE TABLE Discipline (
Id INT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
TeacherId INT NOT NULL,
FOREIGN KEY (TeacherId) REFERENCES Teacher(Id),
);
CREATE TABLE Class (
Id INT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Number INT NOT NULL,
);
CREATE TABLE Lesson (
Id INT PRIMARY KEY,
DateTimeLesson SMALLDATETIME,
DisciplineId INT NOT NULL,
TeacherId INT NOT NULL,
ClassId INT NOT NULL,
FOREIGN KEY (DisciplineId) REFERENCES Discipline(Id),
FOREIGN KEY (TeacherId) REFERENCES Teacher(Id),
FOREIGN KEY (ClassId) REFERENCES Class(Id),
);
CREATE TABLE GroupLesson  (
GroupId INT NOT NULL,
LessonId INT NOT NULL,
FOREIGN KEY (GroupId) REFERENCES SomeGroup(Id),
FOREIGN KEY (LessonId) REFERENCES Lesson(Id),
PRIMARY KEY (GroupId, LessonId)
);