CREATE TABLE SomeUser (
Id INT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
RegistrationDate DATE,
);
CREATE TABLE Role (
Id INT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
);
CREATE TABLE UserRole  (
SomeUserId INT NOT NULL,
RoleId INT NOT NULL,
FOREIGN KEY (SomeUserId) REFERENCES SomeUser(Id),
FOREIGN KEY (RoleId) REFERENCES Role(Id),
PRIMARY KEY (SomeUserId, RoleId)
);
CREATE TABLE Task (
Id INT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
IsCompleted BIT NOT NULL,
);
CREATE TABLE TaskUser (
SomeUserId INT NOT NULL,
TaskId INT NOT NULL,
FOREIGN KEY (SomeUserId) REFERENCES SomeUser(Id),
FOREIGN KEY (TaskId) REFERENCES Task(Id),
PRIMARY KEY (SomeUserId, TaskId)
);